      - name: Mark Deployment as Successful on GitHub
        if: success()
        uses: chrnorm/deployment-status@v2
        with:
          token: ${{ secrets.DEPLOY_PAT }}
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}
          state: success

      - name: Mark Deployment as Failed on GitHub
        if: failure()
        uses: chrnorm/deployment-status@v2
        with:
          token: ${{ secrets.DEPLOY_PAT }}
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}
          state: failure
