name: Deploy to Render and Notify GitHub

on:
  push:
    branches:
      - main

jobs:
  render-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Notify GitHub of Deployment
        id: deployment
        uses: chrnorm/deployment-action@v2
        with:
          token: ${{ secrets.DEPLOY_PAT }}
          environment: production
          description: "Starting deployment to Render"
          transient_environment: true
          auto_inactive: true

      - name: Trigger Render Deploy and Capture ID
        id: render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          echo "Triggering Render deploy..."
          response=$(curl -s -X POST "https://api.render.com/deploy/srv-d1hs5cripnbc73fk74tg?key=$RENDER_API_KEY")
          echo "Response: $response"
          # Check if response is valid JSON and extract deploy ID
          if echo "$response" | jq -e . >/dev/null 2>&1; then
            deploy_id=$(echo "$response" | jq -r '.deploy.id // empty')
          else
            echo "❌ Response is not valid JSON: $response"
            exit 1
          fi
          if [ -z "$deploy_id" ]; then
            echo "❌ Could not extract deploy ID from response: $response"
            exit 1
          fi
          echo "RENDER_DEPLOY_ID=$deploy_id" >> $GITHUB_ENV

      - name: Wait for Render Deploy to Complete
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          echo "Waiting for Render deployment to finish..."
          for i in {1..20}; do
            status_response=$(curl -s -H "Authorization: Bearer $RENDER_API_KEY" \
              https://api.render.com/v1/deploys/$RENDER_DEPLOY_ID)
            echo "Status Response: $status_response"
            if echo "$status_response" | jq -e '.status' >/dev/null 2>&1; then
              status=$(echo "$status_response" | jq -r '.status // "unknown"')
            else
              status="unknown"
            fi
            echo "[$i] Status: $status"
            if [[ "$status" == "live" ]]; then
              echo "✅ Render deployment successful"
              exit 0
            elif [[ "$status" == "build_failed" || "$status" == "update_failed" ]]; then
              echo "❌ Render deployment failed"
              exit 1
            fi
            sleep 10
          done
          echo "⏱️ Timed out waiting for Render deployment"
          exit 1

      - name: Mark Deployment as Successful on GitHub
        if: success()
        uses: chrnorm/deployment-status@v2
        with:
          token: ${{ secrets.DEPLOY_PAT }}
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}
          state: success
          environment-url: https://geoclock.onrender.com

      - name: Mark Deployment as Failed on GitHub
        if: failure()
        uses: chrnorm/deployment-status@v2
        with:
          token: ${{ secrets.DEPLOY_PAT }}
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}
          state: failure
